<?php

/**
 * THIS FOLDER REFERENCE FILES OF THE PARENT THEME
 * 
 * EACH FILE IN THIS FOLDER REFERENCE ANOTHER PHP FILE IN FOLDER /templates
 * 
 * PLEASE MODIFY FILES IN THIS FOLDER WITH CAUTION
 */
